CREATE TABLE reminders (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, user_id INT, time INT, title VARCHAR(32), content TEXT, `repeat` VARCHAR(8) DEFAULT '');
CREATE TABLE users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, email VARCHAR(256), password VARCHAR(128), salt VARCHAR(64), timezone VARCHAR(32) DEFAULT '');
